# Generated by Django 3.2.5 on 2021-08-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0009_auto_20210815_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostelN', models.CharField(max_length=100)),
                ('Article', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('PlaceFound', models.TextField()),
                ('Details', models.TextField()),
                ('Name', models.CharField(max_length=100)),
                ('LDAP', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=100)),
                ('AddressItem', models.CharField(max_length=300)),
                ('Image', models.ImageField(upload_to='Found')),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Pending', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostelN', models.CharField(max_length=100)),
                ('Article', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('PlaceLost', models.TextField()),
                ('Details', models.TextField()),
                ('Name', models.CharField(max_length=100)),
                ('LDAP', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=100)),
                ('AddressItem', models.CharField(max_length=300)),
                ('Image', models.ImageField(upload_to='Lost')),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Pending', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LostList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('short', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='FoundList',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
