# Generated by Django 3.2.5 on 2021-08-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0010_auto_20210817_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Position', models.CharField(max_length=400)),
                ('Contact', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
