# Generated by Django 3.2.5 on 2021-08-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0011_contactoffice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lostlist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lostlist',
            name='short',
        ),
        migrations.RemoveField(
            model_name='lostlist',
            name='title',
        ),
        migrations.AddField(
            model_name='lostlist',
            name='LostItem',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Work.lost'),
        ),
        migrations.AddField(
            model_name='lostlist',
            name='Status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Pending'),
        ),
    ]
