# Generated by Django 3.2.5 on 2021-08-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0012_auto_20210817_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost',
            name='Image',
        ),
    ]
