# Generated by Django 3.2.5 on 2021-08-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0014_auto_20210817_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='found',
            name='Image',
        ),
        migrations.AddField(
            model_name='found',
            name='ImageFound',
            field=models.ImageField(blank=True, upload_to='Found'),
        ),
        migrations.AddField(
            model_name='lost',
            name='ImageLost',
            field=models.ImageField(blank=True, upload_to='Lost'),
        ),
    ]
