# Generated by Django 3.2.5 on 2021-08-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0015_auto_20210818_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='ImageLost',
            field=models.ImageField(upload_to='Lost'),
        ),
    ]
