# Generated by Django 3.2.5 on 2021-08-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0016_alter_lost_imagelost'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='found',
            name='ImageFound',
            field=models.ImageField(upload_to='Found'),
        ),
        migrations.AlterField(
            model_name='found',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Solved', 'Solved')], default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='lost',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Solved', 'Solved')], default='Pending', max_length=200),
        ),
    ]
